=== inviqa/MX_HelperBar/src/etc/command.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:include schemaLocation="urn:magento:framework:Acl/etc/acl.xsd"/>

    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="command" type="commandElement" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="commandElement">
        <xs:all>
            <xs:element name="resource" type="aclResource" minOccurs="1" maxOccurs="1"/>
            <xs:element name="label" type="xs:string"></xs:element>
            <xs:element name="handle_url" type="urlType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="options" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="urlType">
        <xs:restriction base="xs:anyURI">
            <xs:minLength value="4"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== inviqa/MX_HelperBar/src/etc/commands.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:MX_ModuleHelperBar:etc/command.xsd">
    <command name="clear_cache">
        <resource>Magento_Backend::cache</resource>
        <label>Clear Cache</label>
        <handleUrl>helperbar/ajax_cache/massRefresh</handleUrl>
        <options>MX\HelperBar\Model\Commands\Options\ClearCache</options>
    </command>
    <command name="template_path_hints">
        <resource>Magento_Config::dev</resource>
        <label>Template Path Hints</label>
        <handleUrl>helperbar/ajax_config/templatePathHints</handleUrl>
        <options>MX\HelperBar\Model\Commands\Options\TemplatePathHints</options>
    </command>
</config>

=== inviqa/MX_HelperBar/src/etc/command.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:MX_ModuleHelperBar:etc/command.xsd">
    <command id="clear_cache">
        <resource>Magento_Backend::cache</resource>
        <label>Clear Cache</label>
        <handle_url>helperbar/ajax_cache/massRefresh</handle_url>
        <options>MX\HelperBar\Model\Commands\ClearCache</options>
    </command>
    <command id="template_path_hints">
        <resource>Magento_Config::dev</resource>
        <label>Template Path Hints</label>
        <handle_url>helperbar/ajax_config/templatePathHints</handle_url>
        <options>MX\HelperBar\Model\Commands\TemplatePathHints</options>
    </command>
</config>
